# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='local_name',
            field=models.CharField(default='', max_length=100, verbose_name='Название'),
        ),
    ]
