# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_local_name'),
    ]

    operations = [
#        migrations.AlterField(
#            model_name='city',
#            name='local_name',
#            field=models.CharField(default='', max_length=100, verbose_name='Название (рус.)'),
#        ),
    ]
