# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-08 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_auto_20180608_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecity',
            name='city',
        ),
        migrations.RemoveField(
            model_name='favoritecity',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavoriteCity',
        ),
    ]
